export { useGetAparelhos, APARELHOS_QUERY_KEY } from './use-get-aparelhos'
export { useGetAparelho } from './use-get-aparelho'
export { useCreateAparelho } from './use-create-aparelho'
export { useUpdateAparelho } from './use-update-aparelho'
export { useDeleteAparelho } from './use-delete-aparelho'
