export * from './aparelho.keys'
export { useCreateAparelho } from './use-create-aparelho'
export { useDeleteAparelho } from './use-delete-aparelho'
export { useGetAparelho } from './use-get-aparelho'
export { useGetAparelhos } from './use-get-aparelhos'
export { useUpdateAparelho } from './use-update-aparelho'
